"""1.2.8

Revision ID: 737c07183bff
Revises: b5817f5725fc
Create Date: 2024-04-18 16:50:33.453566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '737c07183bff'
down_revision = 'b5817f5725fc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('SITE_BRUSH_TASK', 'STOP_RULE',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('SITE_BRUSH_TASK', 'STOP_RULE',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
