"""1.3.0

Revision ID: 9054013d8038
Revises: 737c07183bff
Create Date: 2024-10-18 12:20:51.777726

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9054013d8038'
down_revision = '737c07183bff'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('SITE_BRUSH_TASK', sa.Column('TIME_RANGE', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('SITE_BRUSH_TASK', 'TIME_RANGE')
    # ### end Alembic commands ###
