"""1.3.0

Revision ID: 9054013d8038
Revises: 737c07183bff
Create Date: 2024-10-18 12:20:51.777726

"""
from alembic import op
import sqlalchemy as sa
from alembic import context


# revision identifiers, used by Alembic.
revision = '9054013d8038'
down_revision = '737c07183bff'
branch_labels = None
depends_on = None


def has_column(table_name, column_name):
    """检查表中是否已存在指定列"""
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = inspector.get_columns(table_name)
    return any(col['name'] == column_name for col in columns)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 检查 TIME_RANGE 列是否已存在，避免重复添加
    if not has_column('SITE_BRUSH_TASK', 'TIME_RANGE'):
        op.add_column('SITE_BRUSH_TASK', sa.Column('TIME_RANGE', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 检查 TIME_RANGE 列是否存在，存在时才删除
    if has_column('SITE_BRUSH_TASK', 'TIME_RANGE'):
        op.drop_column('SITE_BRUSH_TASK', 'TIME_RANGE')
    # ### end Alembic commands ###
