"""1.3.1

Revision ID: a933386acbad
Revises: 9054013d8038
Create Date: 2026-03-15 16:46:35.654189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a933386acbad'
down_revision = '9054013d8038'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('MESSAGE_CLIENT', sa.Column('TEMPLATES', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('MESSAGE_CLIENT', 'TEMPLATES')
    # ### end Alembic commands ###
