"""1.2.8

Revision ID: b5817f5725fc
Revises: a19a48dbb41b
Create Date: 2024-04-18 13:42:56.601190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5817f5725fc'
down_revision = 'a19a48dbb41b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        with op.batch_alter_table("SITE_BRUSH_TASK") as batch_op:
            batch_op.add_column(sa.Column('STOP_RULE', sa.TEXT, nullable=True, default=""))
    except Exception as e:
        pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
        pass
    # ### end Alembic commands ###
