#!/usr/bin/with-contenv bash
# shellcheck shell=bash

umask ${UMASK}

exec \
    s6-notifyoncheck -d -n 300 -w 1000 -c "nc -z localhost ${NT_PORT}" \
    cd ${WORKDIR} s6-setuidgid nt sh ./start-server.sh