"""1.3.2

Revision ID: 6766a9cd1d4b
Revises: a933386acbad
Create Date: 2026-04-10 11:50:00.000000

"""

import ast
import json
import os

import ruamel.yaml
import sqlalchemy as sa
from sqlalchemy import Column, Integer, Sequence, String, Text

from alembic import op

# revision identifiers, used by Alembic.
revision = "6766a9cd1d4b"
down_revision = "a933386acbad"
branch_labels = None
depends_on = None


def has_table(table_name):
    """检查表是否已存在"""
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    return table_name in inspector.get_table_names()


def _fix_rule(val):
    """将旧的 Python 字面量规则字符串清洗为合法 JSON"""
    if not val:
        return "{}"
    val = val.strip()
    if not val:
        return "{}"
    # 处理被单引号或双引号包围的空字符串
    if val in ("''", '""', "'", '"'):
        return "{}"
    # 已经是 JSON 格式，直接返回
    try:
        json.loads(val)
        return val
    except Exception:
        pass
    # 处理被外层引号包裹的情况（如 "'{...}'" 或 '"{...}"'）
    if (val.startswith("'") and val.endswith("'")) or (val.startswith('"') and val.endswith('"')):
        inner = val[1:-1]
        try:
            # 尝试解析内部内容
            json.loads(inner)
            return inner
        except Exception:
            pass
        try:
            d = ast.literal_eval(inner)
            return json.dumps(d, ensure_ascii=False)
        except Exception:
            pass
    # 处理 Python 单引号字典格式
    try:
        d = ast.literal_eval(val)
        return json.dumps(d, ensure_ascii=False)
    except Exception:
        pass
    # 其他情况返回空对象
    return "{}"


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    if not has_table("MEDIASERVER"):
        op.create_table(
            "MEDIASERVER",
            Column("ID", Integer, Sequence("ID"), primary_key=True),
            Column("NAME", String(255), nullable=False),
            Column("ENABLED", Integer, nullable=False, server_default="0"),
            Column("CONFIG", Text),
            Column("IS_DEFAULT", Integer, nullable=False, server_default="0"),
            Column("NOTE", Text),
        )
        op.create_index("ix_MEDIASERVER_NAME", "MEDIASERVER", ["NAME"], unique=False)

    # 尝试从配置文件迁移现有媒体服务器配置到数据库
    try:
        config_path = os.environ.get("NEXUS_MEDIA_CONFIG")
        if config_path:
            with open(config_path, encoding="utf-8") as cf:
                cfg = ruamel.yaml.YAML().load(cf)
            if cfg:
                media_server_type = cfg.get("media", {}).get("media_server", "emby")
                server_map = {
                    "emby": cfg.get("emby"),
                    "jellyfin": cfg.get("jellyfin"),
                    "plex": cfg.get("plex"),
                    "fnos": cfg.get("fnos"),
                }
                conn = op.get_bind()
                for name, config in server_map.items():
                    if config:
                        enabled = 1 if name == media_server_type else 0
                        is_default = 1 if name == media_server_type else 0
                        # 检查是否已存在
                        result = conn.execute(
                            sa.text("SELECT ID FROM MEDIASERVER WHERE NAME = :name"), {"name": name}
                        ).fetchone()
                        if not result:
                            conn.execute(
                                sa.text(
                                    "INSERT INTO MEDIASERVER (NAME, ENABLED, CONFIG, IS_DEFAULT) "
                                    "VALUES (:name, :enabled, :config, :is_default)"
                                ),
                                {
                                    "name": name,
                                    "enabled": enabled,
                                    "config": json.dumps(config) if config else None,
                                    "is_default": is_default,
                                },
                            )
    except Exception:
        pass

    # 修改 SEARCH_RESULT_INFO 表的 ENCLOSURE 字段长度，兼容 magnet 长链接
    try:
        with op.batch_alter_table("SEARCH_RESULT_INFO") as batch_op:
            batch_op.alter_column("ENCLOSURE", type_=sa.String(8192), existing_type=sa.String(255))
    except Exception:
        pass

    # 修改 SEARCH_RESULT_INFO 表的 SIZE 字段类型为 BigInteger，兼容超过 2GB 的种子大小
    try:
        with op.batch_alter_table("SEARCH_RESULT_INFO") as batch_op:
            batch_op.alter_column("SIZE", type_=sa.BigInteger(), existing_type=sa.Integer())
    except Exception:
        pass

    # 修改 CONFIG_SITE 表的 SIZE 字段类型为 BigInteger，并转换旧数据
    try:
        conn = op.get_bind()
        # 先读取并转换旧数据
        rows = conn.execute(sa.text("SELECT ID, SIZE FROM CONFIG_SITE")).fetchall()
        for row in rows:
            size_val = row[1]
            if size_val:
                try:
                    size_bytes = int(float(size_val) * 1024**3)
                except (ValueError, TypeError):
                    size_bytes = 0
                conn.execute(
                    sa.text("UPDATE CONFIG_SITE SET SIZE = :size WHERE ID = :id"), {"size": size_bytes, "id": row[0]}
                )
        with op.batch_alter_table("CONFIG_SITE") as batch_op:
            batch_op.alter_column("SIZE", type_=sa.BigInteger(), existing_type=sa.String(255))
    except Exception:
        pass

    # 修改 SITE_BRUSH_TASK 表的 SEED_SIZE 字段类型为 BigInteger，并转换旧数据
    try:
        conn = op.get_bind()
        rows = conn.execute(sa.text("SELECT ID, SEED_SIZE FROM SITE_BRUSH_TASK")).fetchall()
        for row in rows:
            size_val = row[1]
            if size_val:
                try:
                    size_bytes = int(float(size_val) * 1024**3)
                except (ValueError, TypeError):
                    size_bytes = 0
                conn.execute(
                    sa.text("UPDATE SITE_BRUSH_TASK SET SEED_SIZE = :size WHERE ID = :id"),
                    {"size": size_bytes, "id": row[0]},
                )
        with op.batch_alter_table("SITE_BRUSH_TASK") as batch_op:
            batch_op.alter_column("SEED_SIZE", type_=sa.BigInteger(), existing_type=sa.String(255))
    except Exception:
        pass

    # 修改 DOWNLOAD_HISTORY 表的 ENCLOSURE 字段长度，兼容 magnet 长链接
    try:
        with op.batch_alter_table("DOWNLOAD_HISTORY") as batch_op:
            batch_op.alter_column("ENCLOSURE", type_=sa.String(8192), existing_type=sa.String(512))
    except Exception:
        pass

    # 修改 RSS_TORRENTS 表的 ENCLOSURE 字段长度，兼容 magnet 长链接
    try:
        with op.batch_alter_table("RSS_TORRENTS") as batch_op:
            batch_op.alter_column("ENCLOSURE", type_=sa.String(8192), existing_type=sa.String(512))
    except Exception:
        pass

    # 修改 SITE_BRUSH_TORRENTS 表的 ENCLOSURE 字段长度，兼容 magnet 长链接
    try:
        with op.batch_alter_table("SITE_BRUSH_TORRENTS") as batch_op:
            batch_op.alter_column("ENCLOSURE", type_=sa.String(8192), existing_type=sa.String(512))
    except Exception:
        pass

    # 将 SITE_BRUSH_TASK 表中的规则字段从 Python 字面量清洗为合法 JSON
    try:
        conn = op.get_bind()
        rows = conn.execute(sa.text("SELECT ID, RSS_RULE, REMOVE_RULE, STOP_RULE FROM SITE_BRUSH_TASK")).fetchall()
        for row in rows:
            rid, rss_rule, remove_rule, stop_rule = row
            conn.execute(
                sa.text("UPDATE SITE_BRUSH_TASK SET RSS_RULE=:rss, REMOVE_RULE=:remove, STOP_RULE=:stop WHERE ID=:rid"),
                {
                    "rss": _fix_rule(rss_rule),
                    "remove": _fix_rule(remove_rule),
                    "stop": _fix_rule(stop_rule),
                    "rid": rid,
                },
            )
    except Exception:
        pass

    # 修改 SYSTEM_DICT 表的 VALUE 字段类型为 Text，避免配置被截断
    try:
        with op.batch_alter_table("SYSTEM_DICT") as batch_op:
            batch_op.alter_column("VALUE", type_=sa.Text(), existing_type=sa.String(255))
    except Exception:
        pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        with op.batch_alter_table("SITE_BRUSH_TORRENTS") as batch_op:
            batch_op.alter_column("ENCLOSURE", type_=sa.String(512), existing_type=sa.String(8192))
    except Exception:
        pass
    try:
        with op.batch_alter_table("RSS_TORRENTS") as batch_op:
            batch_op.alter_column("ENCLOSURE", type_=sa.String(512), existing_type=sa.String(8192))
    except Exception:
        pass
    try:
        with op.batch_alter_table("DOWNLOAD_HISTORY") as batch_op:
            batch_op.alter_column("ENCLOSURE", type_=sa.String(512), existing_type=sa.String(8192))
    except Exception:
        pass
    try:
        with op.batch_alter_table("SEARCH_RESULT_INFO") as batch_op:
            batch_op.alter_column("ENCLOSURE", type_=sa.String(255), existing_type=sa.String(8192))
    except Exception:
        pass
    try:
        with op.batch_alter_table("SEARCH_RESULT_INFO") as batch_op:
            batch_op.alter_column("SIZE", type_=sa.Integer(), existing_type=sa.BigInteger())
    except Exception:
        pass
    try:
        with op.batch_alter_table("SYSTEM_DICT") as batch_op:
            batch_op.alter_column("VALUE", type_=sa.String(255), existing_type=sa.Text())
    except Exception:
        pass
    if has_table("MEDIASERVER"):
        op.drop_table("MEDIASERVER")
    # ### end Alembic commands ###
