"""1.2.8

Revision ID: 737c07183bff
Revises: b5817f5725fc
Create Date: 2024-04-18 16:50:33.453566

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "737c07183bff"
down_revision = "b5817f5725fc"
branch_labels = None
depends_on = None


def has_table(table_name):
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    return inspector.has_table(table_name)


def has_column(table_name, column_name):
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    if not inspector.has_table(table_name):
        return False
    columns = inspector.get_columns(table_name)
    return any(col["name"] == column_name for col in columns)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    if has_table("SITE_BRUSH_TASK") and has_column("SITE_BRUSH_TASK", "STOP_RULE"):
        op.alter_column("SITE_BRUSH_TASK", "STOP_RULE", existing_type=sa.TEXT())
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    if has_table("SITE_BRUSH_TASK") and has_column("SITE_BRUSH_TASK", "STOP_RULE"):
        op.alter_column("SITE_BRUSH_TASK", "STOP_RULE", existing_type=sa.TEXT(), nullable=True)
    # ### end Alembic commands ###
