"""
RBAC 领域 Repository 接口（Python Protocol）
定义 RBAC（用户、角色、权限、菜单、日志）的仓储契约
"""

from typing import Any, Protocol

from app.domain.entities.rbac import (
    RBACMenuEntity,
    RBACOperationLogEntity,
    RBACPermissionEntity,
    RBACRoleEntity,
    RBACUserEntity,
    RBACUserLoginLogEntity,
)


class IRBACUserRepository(Protocol):
    """RBAC用户仓储接口"""

    def get_user_by_id(self, user_id: int) -> RBACUserEntity | None: ...
    def get_user_by_username(self, username: str) -> RBACUserEntity | None: ...
    def get_user_by_email(self, email: str) -> RBACUserEntity | None: ...
    def get_users(
        self, page: int = 1, page_size: int = 20, status: int | None = None
    ) -> tuple[list[RBACUserEntity], int]: ...
    def get_all_users(self) -> list[RBACUserEntity]: ...
    def is_user_exists(self, username: str) -> bool: ...
    def is_email_exists(self, email: str) -> bool: ...
    def create_user(
        self,
        username: str,
        password_hash: str,
        email: str | None = None,
        nickname: str | None = None,
    ) -> RBACUserEntity: ...
    def update_user(self, user_id: int, **kwargs) -> bool: ...
    def update_last_login(self, user_id: int, ip: str | None = None) -> bool: ...
    def delete_user(self, user_id: int) -> bool: ...
    def hard_delete_user(self, user_id: int) -> bool: ...
    def get_user_roles(self, user_id: int) -> list[RBACRoleEntity]: ...
    def assign_roles_to_user(self, user_id: int, role_ids: list[int]) -> bool: ...
    def add_role_to_user(self, user_id: int, role_id: int) -> bool: ...
    def remove_role_from_user(self, user_id: int, role_id: int) -> bool: ...


class IRBACRoleRepository(Protocol):
    """RBAC角色仓储接口"""

    def get_role_by_id(self, role_id: int) -> RBACRoleEntity | None: ...
    def get_role_by_code(self, role_code: str) -> RBACRoleEntity | None: ...
    def get_all_roles(self, status: int | None = None) -> list[RBACRoleEntity]: ...
    def get_roles_page(self, page: int = 1, page_size: int = 20) -> tuple[list[RBACRoleEntity], int]: ...
    def is_role_exists(self, role_code: str) -> bool: ...
    def create_role(
        self, role_name: str, role_code: str, description: str | None = None, role_level: int = 100
    ) -> RBACRoleEntity: ...
    def update_role(self, role_id: int, **kwargs) -> bool: ...
    def delete_role(self, role_id: int) -> bool: ...
    def get_role_permissions(self, role_id: int) -> list[RBACPermissionEntity]: ...
    def assign_permissions_to_role(self, role_id: int, permission_ids: list[int]) -> bool: ...
    def get_role_menus(self, role_id: int) -> list[RBACMenuEntity]: ...
    def assign_menus_to_role(self, role_id: int, menu_ids: list[int]) -> bool: ...


class IRBACPermissionRepository(Protocol):
    """RBAC权限仓储接口"""

    def get_permission_by_id(self, permission_id: int) -> RBACPermissionEntity | None: ...
    def get_permission_by_code(self, permission_code: str) -> RBACPermissionEntity | None: ...
    def get_all_permissions(
        self, module: str | None = None, permission_type: str | None = None
    ) -> list[RBACPermissionEntity]: ...
    def get_permissions_by_codes(self, codes: list[str]) -> list[RBACPermissionEntity]: ...
    def create_permission(
        self,
        permission_name: str,
        permission_code: str,
        permission_type: str = "api",
        module: str | None = None,
        description: str | None = None,
    ) -> RBACPermissionEntity: ...
    def update_permission(self, permission_id: int, **kwargs) -> bool: ...
    def delete_permission(self, permission_id: int) -> bool: ...


class IRBACMenuRepository(Protocol):
    """RBAC菜单仓储接口"""

    def get_menu_by_id(self, menu_id: int) -> RBACMenuEntity | None: ...
    def get_menu_by_code(self, menu_code: str, include_hidden: bool = True) -> RBACMenuEntity | None: ...
    def get_all_menus(self, status: int | None = None) -> list[RBACMenuEntity]: ...
    def get_top_menus(self, include_hidden: bool = False) -> list[RBACMenuEntity]: ...
    def get_children_menus(self, parent_id: int) -> list[RBACMenuEntity]: ...
    def get_menu_tree(self, include_hidden: bool = False) -> list[dict[str, Any]]: ...
    def get_user_menus(self, user_id: int) -> list[RBACMenuEntity]: ...
    def create_menu(
        self,
        menu_name: str,
        menu_code: str,
        parent_id: int | None = None,
        path: str | None = None,
        icon: str | None = None,
        component: str | None = None,
        sort_order: int = 0,
        menu_level: int = 1,
        permission_code: str | None = None,
    ) -> RBACMenuEntity: ...
    def update_menu(self, menu_id: int, **kwargs) -> bool: ...
    def delete_menu(self, menu_id: int) -> bool: ...


class IRBACLogRepository(Protocol):
    """RBAC日志仓储接口"""

    def add_login_log(
        self,
        user_id: int | None,
        username: str,
        login_ip: str | None = None,
        login_location: str | None = None,
        user_agent: str | None = None,
        login_type: str = "password",
        login_status: int = 1,
        fail_reason: str | None = None,
    ) -> RBACUserLoginLogEntity: ...
    def get_login_logs(
        self, user_id: int | None = None, page: int = 1, page_size: int = 20
    ) -> tuple[list[RBACUserLoginLogEntity], int]: ...
    def add_operation_log(
        self,
        user_id: int | None = None,
        username: str | None = None,
        module: str | None = None,
        operation_type: str = "QUERY",
        description: str | None = None,
        request_method: str | None = None,
        request_url: str | None = None,
        request_params: str | None = None,
        response_data: str | None = None,
        operation_ip: str | None = None,
        execution_time: int | None = None,
        operation_status: int = 1,
        error_msg: str | None = None,
    ) -> RBACOperationLogEntity: ...
    def get_operation_logs(
        self, user_id: int | None = None, module: str | None = None, page: int = 1, page_size: int = 20
    ) -> tuple[list[RBACOperationLogEntity], int]: ...
