"""
转移领域 Repository 接口（Python Protocol）
"""

from typing import Any, Protocol

from app.domain.entities.transfer import (
    TransferHistoryEntity,
    TransferUnknownEntity,
)


class ITransferHistoryRepository(Protocol):
    """转移历史仓储接口"""

    # 新接口方法
    def is_exists(self, source_path: str, source_filename: str, dest_path: str, dest_filename: str) -> bool: ...

    def insert(self, in_from, rmt_mode, in_path, out_path, dest, media_info) -> None: ...

    def get_page(self, search: str | None, page: int, rownum: int) -> tuple[int, list[TransferHistoryEntity]]: ...

    def get_by_id(self, logid: int) -> TransferHistoryEntity | None: ...

    def get_by_tmdb(
        self, tmdbid: int, season: str | None = None, season_episode: str | None = None
    ) -> list[TransferHistoryEntity]: ...

    def delete(self, logid: int) -> None: ...

    def delete_transfer_logs(self, logids: list[int]) -> None: ...

    def delete_by_source(self, source_path: str, source_filename: str) -> None: ...

    # 兼容旧Repository方法名
    def is_sync_in_history(self, path: str, dest: str) -> bool: ...

    def insert_sync_history(self, path: str, src: str, dest: str) -> None: ...

    def get_transfer_info_by(self, tmdbid, season=None, season_episode=None): ...

    def get_contiguous_transferred_episode_by_tmdb(self, tmdbid, season: int | None = None, start: int = 1) -> int: ...

    def get_transfer_info_by_id(self, logid): ...

    def get_transfer_history(self, search, page, rownum): ...

    def delete_transfer_log_by_id(self, logid): ...

    def delete_transfer(self): ...

    def get_transfer_statistics(self, days: int = 30): ...

    def get_transfer_series_statistics(self, days: int = 30): ...

    # 兼容旧Repository方法名 - 委托给Unknown子适配器
    def delete_transfer_unknown(self, tid) -> None: ...

    def delete_transfer_unknowns(self, tids: list[int]) -> None: ...

    def get_unknown_info_by_id(self, tid): ...

    def update_transfer_unknown_state(self, path): ...

    def get_transfer_unknown_paths(self): ...

    def is_transfer_unknown_exists(self, path: str): ...

    def get_transfer_unknown_paths_by_page(self, search, page, rownum): ...

    # 兼容旧Repository方法名 - 委托给Blacklist子适配器
    def delete_transfer_blacklist(self, path): ...

    def truncate_transfer_blacklist(self): ...

    # 兼容旧Repository方法名
    def is_transfer_notin_blacklist(self, path: str) -> bool: ...

    def is_need_insert_transfer_unknown(self, path: str) -> bool: ...

    def insert_transfer_unknown(self, path: str, dest: Any, rmt_mode: Any) -> None: ...

    def insert_transfer_history(
        self,
        in_from: Any,
        rmt_mode: Any,
        in_path: str,
        out_path: str,
        dest: str,
        media_info: Any,
        dst_backend: str | None = None,
    ) -> None: ...


class ITransferUnknownRepository(Protocol):
    """未知转移记录仓储接口"""

    def insert(self, path: str, dest: str, mode: str) -> None: ...

    def get_all(self) -> list[TransferUnknownEntity]: ...

    def get_by_id(self, tid: int) -> TransferUnknownEntity | None: ...

    def is_exists(self, path: str) -> bool: ...

    def delete(self, tid: int) -> None: ...

    def truncate(self) -> None: ...


class ITransferBlacklistRepository(Protocol):
    """转移黑名单仓储接口"""

    def is_exists(self, path: str) -> bool: ...

    def insert(self, path: str) -> None: ...

    def delete(self, path: str) -> None: ...

    def truncate(self) -> None: ...
