"""AppContext 单元测试."""

from unittest.mock import MagicMock

from app.di.context import AppContext


def test_app_context_fields():
    ctx = AppContext(
        event_bus=MagicMock(),
        thread_executor=MagicMock(),
        scheduler_core=MagicMock(),
        message=MagicMock(),
        message_queue=MagicMock(),
        site_cache=MagicMock(),
        site_engine=MagicMock(),
        hook_system=MagicMock(),
        plugin_sandbox=MagicMock(),
        plugin_registry=MagicMock(),
        media_server=MagicMock(),
        apikey_service=MagicMock(),
        media_service=MagicMock(),
        tmdb_client=MagicMock(),
        agent_service=MagicMock(),
        media_recognizer=MagicMock(),
        search_intent_agent=MagicMock(),
        tool_executor=MagicMock(),
        search_orchestrator=MagicMock(),
        downloader_core=MagicMock(),
        download_monitor=MagicMock(),
        filetransfer_service=MagicMock(),
        transfer_pipeline=MagicMock(),
        sync_engine=MagicMock(),
        sync_service=MagicMock(),
        file_index_service=MagicMock(),
        indexer_service=MagicMock(),
        subscribe_service=MagicMock(),
        searcher=MagicMock(),
        rss_task_service=MagicMock(),
        filter_service=MagicMock(),
        torrent_remover_service=MagicMock(),
        brush_task_service=MagicMock(),
        brush_service=MagicMock(),
        site_service=MagicMock(),
        site_resolver=MagicMock(),
        site_favicon_service=MagicMock(),
        media_info_service=MagicMock(),
        media_config_service=MagicMock(),
        media_file_service=MagicMock(),
        media_library_service=MagicMock(),
        media_recommendation_service=MagicMock(),
        media_server_config_service=MagicMock(),
        system_config_service=MagicMock(),
        indexer_config_service=MagicMock(),
        rbac_service=MagicMock(),
        config_service=MagicMock(),
        message_sender_service=MagicMock(),
        message_client_service=MagicMock(),
        scheduler_service=MagicMock(),
        system_info_service=MagicMock(),
        net_test_service=MagicMock(),
        progress_service=MagicMock(),
        web_search_service=MagicMock(),
        backup_restore_service=MagicMock(),
        user_manage_service=MagicMock(),
        tmdb_blacklist_service=MagicMock(),
        download_service=MagicMock(),
        plugin_framework_service=MagicMock(),
        storage_backend_service=MagicMock(),
        search_result_service=MagicMock(),
        transfer_history_service=MagicMock(),
        subscribe_calendar_service=MagicMock(),
        subscribe_history_service=MagicMock(),
        words_service=MagicMock(),
        user_rss_service=MagicMock(),
        subscription_monitor=MagicMock(),
        system_lifecycle=MagicMock(),
        alias_index=MagicMock(),
        edition_graph=MagicMock(),
        identity_resolver=MagicMock(),
        target_matcher=MagicMock(),
        identity_builder=MagicMock(),
        episode_remapper=MagicMock(),
        plugin_market_service=MagicMock(),
    )
    assert ctx.event_bus is not None
    assert ctx.media_service is not None
    assert ctx.system_lifecycle is not None
