"""RBAC 初始化常量定义."""

DEFAULT_PERMISSIONS = [
    {"name": "用户查看", "code": "user:view", "type": "api", "module": "user"},
    {"name": "用户创建", "code": "user:create", "type": "api", "module": "user"},
    {"name": "用户编辑", "code": "user:update", "type": "api", "module": "user"},
    {"name": "用户删除", "code": "user:delete", "type": "api", "module": "user"},
    {"name": "角色查看", "code": "role:view", "type": "api", "module": "role"},
    {"name": "角色创建", "code": "role:create", "type": "api", "module": "role"},
    {"name": "角色编辑", "code": "role:update", "type": "api", "module": "role"},
    {"name": "角色删除", "code": "role:delete", "type": "api", "module": "role"},
    {"name": "权限查看", "code": "permission:view", "type": "api", "module": "permission"},
    {"name": "权限创建", "code": "permission:create", "type": "api", "module": "permission"},
    {"name": "权限编辑", "code": "permission:update", "type": "api", "module": "permission"},
    {"name": "权限删除", "code": "permission:delete", "type": "api", "module": "permission"},
    {"name": "菜单查看", "code": "menu:view", "type": "api", "module": "menu"},
    {"name": "菜单创建", "code": "menu:create", "type": "api", "module": "menu"},
    {"name": "菜单编辑", "code": "menu:update", "type": "api", "module": "menu"},
    {"name": "菜单删除", "code": "menu:delete", "type": "api", "module": "menu"},
    {"name": "系统设置查看", "code": "setting:view", "type": "api", "module": "setting"},
    {"name": "系统设置编辑", "code": "setting:update", "type": "api", "module": "setting"},
    {"name": "媒体库查看", "code": "library:view", "type": "menu", "module": "library"},
    {"name": "媒体库管理", "code": "library:manage", "type": "api", "module": "library"},
    {"name": "站点查看", "code": "site:view", "type": "menu", "module": "site"},
    {"name": "站点管理", "code": "site:manage", "type": "api", "module": "site"},
    {"name": "刷流查看", "code": "brush:view", "type": "menu", "module": "brush"},
    {"name": "刷流管理", "code": "brush:manage", "type": "api", "module": "brush"},
    {"name": "下载查看", "code": "download:view", "type": "menu", "module": "download"},
    {"name": "下载管理", "code": "download:manage", "type": "api", "module": "download"},
    {"name": "订阅查看", "code": "subscription:view", "type": "menu", "module": "rss"},
    {"name": "订阅管理", "code": "subscription:manage", "type": "api", "module": "rss"},
    {"name": "资源搜索", "code": "search:view", "type": "menu", "module": "search"},
    {"name": "执行搜索", "code": "search:execute", "type": "api", "module": "search"},
    {"name": "探索查看", "code": "discovery:view", "type": "menu", "module": "discovery"},
    {"name": "探索管理", "code": "discovery:manage", "type": "api", "module": "discovery"},
    {"name": "服务查看", "code": "service:view", "type": "menu", "module": "service"},
    {"name": "服务管理", "code": "service:manage", "type": "api", "module": "service"},
    {"name": "Agent 查看", "code": "agent:view", "type": "api", "module": "agent"},
    {"name": "Agent 管理", "code": "agent:manage", "type": "api", "module": "agent"},
    {"name": "插件查看", "code": "plugin:view", "type": "menu", "module": "plugin"},
    {"name": "插件管理", "code": "plugin:manage", "type": "api", "module": "plugin"},
    {"name": "日志查看", "code": "log:view", "type": "menu", "module": "log"},
    {"name": "API Key 查看", "code": "apikey:view", "type": "menu", "module": "apikey"},
    {"name": "API Key 创建", "code": "apikey:create", "type": "api", "module": "apikey"},
    {"name": "API Key 编辑", "code": "apikey:update", "type": "api", "module": "apikey"},
    {"name": "API Key 删除", "code": "apikey:delete", "type": "api", "module": "apikey"},
    {"name": "存储后端查看", "code": "storage:view", "type": "menu", "module": "storage"},
    {"name": "存储后端管理", "code": "storage:manage", "type": "api", "module": "storage"},
]


DEFAULT_MENUS = [
    {
        "name": "首页",
        "code": "Home",
        "path": "/dashboard/home",
        "icon": "lucide:layout-dashboard",
        "component": "/dashboard/home/index",
        "sort_order": 0,
        "level": 1,
        "permission_code": "",
    },
    {
        "name": "我的媒体库",
        "code": "Library",
        "path": "/library",
        "icon": "lucide:tv",
        "component": "/media/library/index",
        "sort_order": 1,
        "level": 1,
        "permission_code": "library:view",
    },
    {
        "name": "资源搜索",
        "code": "MediaSearch",
        "path": "/media/search",
        "icon": "lucide:search",
        "component": "/media/search/index",
        "sort_order": 2,
        "level": 1,
        "permission_code": "search:view",
    },
    {
        "name": "探索",
        "code": "Discovery",
        "path": "",
        "icon": "lucide:compass",
        "sort_order": 3,
        "level": 1,
        "permission_code": "discovery:view",
        "children": [
            {
                "name": "排行榜",
                "code": "Ranking",
                "path": "/discovery/ranking",
                "icon": "lucide:trophy",
                "component": "/media/discovery/index",
                "sort_order": 1,
                "level": 2,
                "permission_code": "discovery:view",
            },
            {
                "name": "豆瓣电影",
                "code": "DoubanMovie",
                "path": "/discovery/douban-movie",
                "icon": "lucide:film",
                "component": "/media/discovery/index",
                "sort_order": 2,
                "level": 2,
                "permission_code": "discovery:view",
            },
            {
                "name": "豆瓣电视剧",
                "code": "DoubanTv",
                "path": "/discovery/douban-tv",
                "icon": "lucide:tv",
                "component": "/media/discovery/index",
                "sort_order": 3,
                "level": 2,
                "permission_code": "discovery:view",
            },
            {
                "name": "TMDB电影",
                "code": "TmdbMovie",
                "path": "/discovery/tmdb-movie",
                "icon": "lucide:clapperboard",
                "component": "/media/discovery/index",
                "sort_order": 4,
                "level": 2,
                "permission_code": "discovery:view",
            },
            {
                "name": "TMDB电视剧",
                "code": "TmdbTv",
                "path": "/discovery/tmdb-tv",
                "icon": "lucide:monitor-play",
                "component": "/media/discovery/index",
                "sort_order": 5,
                "level": 2,
                "permission_code": "discovery:view",
            },
            {
                "name": "Bangumi",
                "code": "Bangumi",
                "path": "/discovery/bangumi",
                "icon": "lucide:calendar-days",
                "component": "/media/discovery/index",
                "sort_order": 6,
                "level": 2,
                "permission_code": "discovery:view",
            },
            {
                "name": "更多推荐",
                "code": "DiscoveryRecommend",
                "path": "/discovery/recommend",
                "icon": "lucide:more-horizontal",
                "component": "/media/discovery/recommend",
                "sort_order": 7,
                "level": 2,
                "permission_code": "discovery:view",
                "hide_in_menu": 1,
            },
        ],
    },
    {
        "name": "媒体详情",
        "code": "MediaDetail",
        "path": "/media/detail",
        "icon": "lucide:info",
        "component": "/media/detail/index",
        "sort_order": 999,
        "level": 1,
        "permission_code": "library:view",
        "hide_in_menu": 1,
    },
    {
        "name": "消息中心",
        "code": "MessageCenter",
        "path": "/message-center",
        "icon": "lucide:message-square-text",
        "component": "/message-center/index",
        "sort_order": 4,
        "level": 1,
        "permission_code": "agent:view",
    },
    {
        "name": "知识库",
        "code": "AgentKnowledge",
        "path": "/knowledge",
        "icon": "lucide:library-big",
        "component": "/knowledge/index",
        "sort_order": 4,
        "level": 1,
        "permission_code": "agent:view",
    },
    {
        "name": "站点管理",
        "code": "Site",
        "path": "",
        "icon": "lucide:server",
        "sort_order": 5,
        "level": 1,
        "permission_code": "site:view",
        "children": [
            {
                "name": "站点维护",
                "code": "SiteMaintenance",
                "path": "/site/list",
                "icon": "lucide:server",
                "component": "/site/list/index",
                "sort_order": 1,
                "level": 2,
                "permission_code": "site:view",
            },
            {
                "name": "数据统计",
                "code": "SiteStatistics",
                "path": "/site/statistics",
                "icon": "lucide:clock",
                "component": "/site/statistics/index",
                "sort_order": 2,
                "level": 2,
                "permission_code": "site:view",
            },
            {
                "name": "站点资源",
                "code": "SiteResources",
                "path": "/site/resources",
                "icon": "lucide:database",
                "component": "/site/resources/index",
                "sort_order": 3,
                "level": 2,
                "permission_code": "site:view",
            },
        ],
    },
    {
        "name": "刷流中心",
        "code": "Brush",
        "path": "",
        "icon": "lucide:zap",
        "sort_order": 6,
        "level": 1,
        "permission_code": "brush:view",
        "children": [
            {
                "name": "刷流任务",
                "code": "BrushTask",
                "path": "/brush",
                "icon": "lucide:activity",
                "component": "/brush/index",
                "sort_order": 1,
                "level": 2,
                "permission_code": "brush:manage",
            },
            {
                "name": "刷流规则",
                "code": "BrushRule",
                "path": "/brush/rules",
                "icon": "lucide:filter",
                "component": "/brush/rules/index",
                "sort_order": 2,
                "level": 2,
                "permission_code": "brush:manage",
            },
            {
                "name": "事件日志",
                "code": "BrushEvent",
                "path": "/brush/events",
                "icon": "lucide:scroll-text",
                "component": "/brush/events/index",
                "sort_order": 3,
                "level": 2,
                "permission_code": "brush:view",
            },
        ],
    },
    {
        "name": "订阅管理",
        "code": "Subscription",
        "path": "",
        "icon": "lucide:rss",
        "sort_order": 7,
        "level": 1,
        "permission_code": "subscription:view",
        "children": [
            {
                "name": "电影订阅",
                "code": "MovieSubscription",
                "path": "/subscription/movie",
                "icon": "lucide:film",
                "component": "/subscription/movie/index",
                "sort_order": 1,
                "level": 2,
                "permission_code": "subscription:view",
            },
            {
                "name": "电视剧订阅",
                "code": "TvSubscription",
                "path": "/subscription/tv",
                "icon": "lucide:tv",
                "component": "/subscription/tv/index",
                "sort_order": 2,
                "level": 2,
                "permission_code": "subscription:view",
            },
            {
                "name": "订阅历史",
                "code": "SubscriptionHistory",
                "path": "/subscription/history",
                "icon": "lucide:history",
                "component": "/subscription/history/index",
                "sort_order": 3,
                "level": 2,
                "permission_code": "subscription:view",
            },
            {
                "name": "订阅日历",
                "code": "RssCalendar",
                "path": "/subscription/calendar",
                "icon": "lucide:calendar-days",
                "component": "/subscription/calendar/index",
                "sort_order": 4,
                "level": 2,
                "permission_code": "subscription:view",
            },
            {
                "name": "自定义 RSS",
                "code": "UserRss",
                "path": "/rss-automation",
                "icon": "lucide:file-text",
                "component": "/subscription/user/index",
                "sort_order": 5,
                "level": 2,
                "permission_code": "subscription:manage",
            },
        ],
    },
    {
        "name": "下载管理",
        "code": "Download",
        "path": "",
        "icon": "lucide:download",
        "sort_order": 8,
        "level": 1,
        "permission_code": "library:manage",
        "children": [
            {
                "name": "正在下载",
                "code": "Downloading",
                "path": "/download/downloading",
                "icon": "lucide:loader",
                "component": "/download/downloading/index",
                "sort_order": 1,
                "level": 2,
                "permission_code": "download:view",
            },
            {
                "name": "近期下载",
                "code": "DownloadHistory",
                "path": "/download/history",
                "icon": "lucide:clock",
                "component": "/download/history/index",
                "sort_order": 2,
                "level": 2,
                "permission_code": "download:view",
            },
            {
                "name": "自动删种",
                "code": "TorrentRemove",
                "path": "/download/torrent-remove",
                "icon": "lucide:trash-2",
                "component": "/download/torrent-remove/index",
                "sort_order": 3,
                "level": 2,
                "permission_code": "download:manage",
            },
            {
                "name": "下载设置",
                "code": "DownloadSettings",
                "path": "/download/settings",
                "icon": "lucide:sliders-horizontal",
                "component": "/download/settings/index",
                "sort_order": 4,
                "level": 2,
                "permission_code": "download:manage",
            },
        ],
    },
    {
        "name": "媒体整理",
        "code": "Rename",
        "icon": "lucide:file-text",
        "sort_order": 9,
        "level": 1,
        "permission_code": "library:manage",
        "children": [
            {
                "name": "识别历史",
                "code": "RenameHistory",
                "path": "/rename/history",
                "icon": "lucide:history",
                "component": "/rename/history/index",
                "sort_order": 1,
                "level": 2,
                "permission_code": "library:view",
            },
            {
                "name": "文件管理",
                "code": "RenameMediafile",
                "path": "/rename/mediafile",
                "icon": "lucide:folder-open",
                "component": "/rename/mediafile/index",
                "sort_order": 2,
                "level": 2,
                "permission_code": "library:manage",
            },
            {
                "name": "未识别列表",
                "code": "RenameUnidentification",
                "path": "/rename/unidentification",
                "icon": "lucide:help-circle",
                "component": "/rename/unidentification/index",
                "sort_order": 3,
                "level": 2,
                "permission_code": "library:manage",
            },
            {
                "name": "TMDB 黑名单",
                "code": "RenameBlacklist",
                "path": "/rename/blacklist",
                "icon": "lucide:shield-ban",
                "component": "/rename/blacklist/index",
                "sort_order": 4,
                "level": 2,
                "permission_code": "library:manage",
            },
        ],
    },
    {
        "name": "服务",
        "code": "Service",
        "icon": "lucide:layout-grid",
        "sort_order": 10,
        "level": 1,
        "permission_code": "service:view",
        "children": [
            {
                "name": "服务面板",
                "code": "ServicePanel",
                "path": "/service/panel",
                "icon": "lucide:layout-grid",
                "component": "/service/panel/index",
                "sort_order": 1,
                "level": 2,
                "permission_code": "service:view",
            },
            {
                "name": "调度任务",
                "code": "SchedulerJobs",
                "path": "/service/scheduler",
                "icon": "lucide:clock",
                "component": "/scheduler/jobs/index",
                "sort_order": 2,
                "level": 2,
                "permission_code": "service:view",
            },
        ],
    },
    {
        "name": "系统设置",
        "code": "System",
        "icon": "lucide:settings",
        "sort_order": 11,
        "level": 1,
        "permission_code": "setting:view",
        "children": [
            {
                "name": "基础设置",
                "code": "SystemBasic",
                "path": "/system/basic",
                "icon": "lucide:sliders-horizontal",
                "component": "/system/basic/index",
                "sort_order": 1,
                "level": 2,
                "permission_code": "setting:view",
            },
            {
                "name": "媒体库设置",
                "code": "SystemLibrary",
                "path": "/system/library",
                "icon": "lucide:tv",
                "component": "/system/library/index",
                "sort_order": 2,
                "level": 2,
                "permission_code": "setting:view",
            },
            {
                "name": "分类配置",
                "code": "SystemCategory",
                "path": "/system/category",
                "icon": "lucide:tags",
                "component": "/system/category/index",
                "sort_order": 3,
                "level": 2,
                "permission_code": "setting:view",
            },
            {
                "name": "目录同步",
                "code": "SystemSync",
                "path": "/system/sync",
                "icon": "lucide:refresh-cw",
                "component": "/sync/index",
                "sort_order": 4,
                "level": 2,
                "permission_code": "setting:view",
            },
            {
                "name": "下载器设置",
                "code": "SystemDownloader",
                "path": "/system/downloader",
                "icon": "lucide:download",
                "component": "/download/downloader/index",
                "sort_order": 5,
                "level": 2,
                "permission_code": "setting:view",
            },
            {
                "name": "索引器设置",
                "code": "SystemIndexer",
                "path": "/system/indexer",
                "icon": "lucide:search",
                "component": "/service/indexer/index",
                "sort_order": 6,
                "level": 2,
                "permission_code": "setting:view",
            },
            {
                "name": "媒体服务器",
                "code": "SystemMediaserver",
                "path": "/system/mediaserver",
                "icon": "lucide:server",
                "component": "/service/mediaserver/index",
                "sort_order": 7,
                "level": 2,
                "permission_code": "setting:view",
            },
            {
                "name": "通知设置",
                "code": "SystemNotification",
                "path": "/system/notification",
                "icon": "lucide:bell",
                "component": "/service/notification/index",
                "sort_order": 8,
                "level": 2,
                "permission_code": "setting:view",
            },
            {
                "name": "自定义识别词",
                "code": "SystemWords",
                "path": "/system/words",
                "icon": "lucide:file-text",
                "component": "/words/index",
                "sort_order": 9,
                "level": 2,
                "permission_code": "setting:view",
            },
            {
                "name": "过滤规则",
                "code": "SystemFilter",
                "path": "/system/filter",
                "icon": "lucide:funnel",
                "component": "/filter/rule/index",
                "sort_order": 10,
                "level": 2,
                "permission_code": "setting:view",
            },
            {
                "name": "用户管理",
                "code": "SystemUsers",
                "path": "/system/users",
                "icon": "lucide:users",
                "component": "/system/users/index",
                "sort_order": 11,
                "level": 2,
                "permission_code": "user:view",
            },
            {
                "name": "角色管理",
                "code": "SystemRoles",
                "path": "/system/roles",
                "icon": "lucide:shield",
                "component": "/system/roles/index",
                "sort_order": 12,
                "level": 2,
                "permission_code": "role:view",
            },
            {
                "name": "菜单管理",
                "code": "SystemMenus",
                "path": "/system/menus",
                "icon": "lucide:menu",
                "component": "/system/menus/index",
                "sort_order": 13,
                "level": 2,
                "permission_code": "menu:view",
            },
            {
                "name": "API Key 管理",
                "code": "SystemAPIKey",
                "path": "/system/apikey",
                "icon": "lucide:key",
                "component": "/system/apikey/index",
                "sort_order": 14,
                "level": 2,
                "permission_code": "apikey:view",
            },
            {
                "name": "存储后端",
                "code": "SystemStorage",
                "path": "/system/storage",
                "icon": "lucide:hard-drive",
                "component": "/system/storage/index",
                "sort_order": 15,
                "level": 2,
                "permission_code": "storage:view",
            },
        ],
    },
    {
        "name": "插件中心",
        "code": "Plugin",
        "icon": "lucide:puzzle",
        "sort_order": 12,
        "level": 1,
        "permission_code": "plugin:view",
        "children": [
            {
                "name": "插件市场",
                "code": "PluginMarket",
                "path": "/plugin/market",
                "icon": "lucide:store",
                "component": "/plugin/market/index",
                "sort_order": 1,
                "level": 2,
                "permission_code": "plugin:view",
            },
            {
                "name": "已安装插件",
                "code": "PluginInstalled",
                "path": "/plugin/installed",
                "icon": "lucide:box",
                "component": "/plugin/installed/index",
                "sort_order": 2,
                "level": 2,
                "permission_code": "plugin:view",
            },
        ],
    },
    {
        "name": "日志",
        "code": "Logs",
        "path": "/logs",
        "icon": "lucide:scroll-text",
        "component": "/system/logs/index",
        "sort_order": 13,
        "level": 1,
        "permission_code": "log:view",
    },
    {
        "name": "关于",
        "code": "About",
        "path": "/about",
        "icon": "lucide:copyright",
        "component": "/_core/about/index",
        "sort_order": 9999,
        "level": 1,
        "permission_code": "",
    },
]


DEFAULT_ROLES = [
    {
        "name": "超级管理员",
        "code": "superadmin",
        "description": "拥有系统所有权限",
        "level": 1,
        "all_permissions": True,
        "permissions": [],
        "menus": [],
    },
    {
        "name": "管理员",
        "code": "admin",
        "description": "拥有大部分管理权限",
        "level": 10,
        "permissions": [
            "user:view",
            "user:create",
            "user:update",
            "user:delete",
            "role:view",
            "role:create",
            "role:update",
            "role:delete",
            "permission:view",
            "permission:update",
            "menu:view",
            "menu:create",
            "menu:update",
            "menu:delete",
            "setting:view",
            "setting:update",
            "library:view",
            "library:manage",
            "site:view",
            "site:manage",
            "brush:view",
            "brush:manage",
            "download:view",
            "download:manage",
            "subscription:view",
            "subscription:manage",
            "search:view",
            "search:execute",
            "discovery:view",
            "discovery:manage",
            "service:view",
            "service:manage",
            "agent:view",
            "agent:manage",
            "plugin:view",
            "plugin:manage",
            "log:view",
        ],
        "menus": [
            "Home",
            "MediaSearch",
            "Discovery",
            "Ranking",
            "DoubanMovie",
            "DoubanTv",
            "TmdbMovie",
            "TmdbTv",
            "Bangumi",
            "DiscoveryRecommend",
            "Site",
            "SiteMaintenance",
            "SiteStatistics",
            "SiteResources",
            "Brush",
            "BrushTask",
            "BrushRule",
            "BrushEvent",
            "Subscription",
            "MovieSubscription",
            "TvSubscription",
            "SubscriptionHistory",
            "RssCalendar",
            "UserRss",
            "Download",
            "Downloading",
            "DownloadHistory",
            "TorrentRemove",
            "DownloadSettings",
            "Rename",
            "RenameHistory",
            "RenameMediafile",
            "RenameUnidentification",
            "RenameBlacklist",
            "Service",
            "ServicePanel",
            "SchedulerJobs",
            "Logs",
            "System",
            "SystemBasic",
            "SystemLibrary",
            "SystemCategory",
            "SystemSync",
            "SystemDownloader",
            "SystemIndexer",
            "SystemMediaserver",
            "SystemNotification",
            "SystemWords",
            "SystemFilter",
            "SystemUsers",
            "SystemRoles",
            "SystemMenus",
            "SystemStorage",
            "Plugin",
            "PluginMarket",
            "PluginInstalled",
            "About",
        ],
    },
    {
        "name": "普通用户",
        "code": "user",
        "description": "拥有基本使用权限",
        "level": 100,
        "permissions": [
            "library:view",
            "site:view",
            "download:view",
            "subscription:view",
            "search:view",
            "search:execute",
            "discovery:view",
            "service:view",
        ],
        "menus": [
            "Home",
            "MediaSearch",
            "Discovery",
            "Ranking",
            "DoubanMovie",
            "DoubanTv",
            "TmdbMovie",
            "TmdbTv",
            "Bangumi",
            "DiscoveryRecommend",
            "Site",
            "SiteMaintenance",
            "SiteStatistics",
            "SiteResources",
            "Subscription",
            "MovieSubscription",
            "TvSubscription",
            "SubscriptionHistory",
            "RssCalendar",
            "Download",
            "Downloading",
            "DownloadHistory",
            "Rename",
            "RenameHistory",
            "Service",
            "ServicePanel",
            "About",
        ],
    },
    {
        "name": "访客",
        "code": "guest",
        "description": "仅拥有查看权限",
        "level": 200,
        "permissions": ["library:view", "search:view", "discovery:view"],
        "menus": [
            "Home",
            "MediaSearch",
            "Discovery",
            "Ranking",
            "DoubanMovie",
            "DoubanTv",
            "TmdbMovie",
            "TmdbTv",
            "Bangumi",
            "DiscoveryRecommend",
        ],
    },
]
